### ISSUE TITLE
Java 17 Compatability

### ISSUE THREAD

**Issue by uccu-jacobh** [mulesoft/data-weave-jwt-library#37]
I see some commits that seem to be attempting to update this library to be Java 17 compatible, but there have been no new releases since v1.0.0 in 2022. Is this still on the roadmap? 

Java 8 compatible runtimes will reach End of Extended Support in June 2025, so this library will be obsolete by then if Java 17 compatibility is not achieved.
 
We are using this library to generate JWTs for accessing the DocuSign API on one of our Mule apps. When we try upgrading to Java 17 runtime, we start getting a reflection error from this library due to the strong encapsulation of Java 17.

Dataweave Script
```
%dw 2.0
import * from jwt::RSA

output application/json
var key = Mule::p('secure::docusign.auth.private_key')
var date = now()
---
{
	token: JWT(
		{
		  	"alg": "RS256",
		  	"typ": "JWT"
		},
		{
			iss: Mule::p('secure::docusign.auth.integration_key'),
			sub: Mule::p('secure::docusign.auth.user_id'),
			aud: Mule::p('docusign.auth.aud'),
			iat: date as Number { unit: 'seconds' },
			exp: (date + |PT3600S|) as Number { unit: 'seconds' },
			scope: Mule::p('docusign.auth.scope'),
		},
		key,
		"Sha256withRSA"
	),
	expiration: date + |PT3600S|
}
```

Error
```
********************************************************************************
Message               : "org.mule.weave.v2.module.pojo.exception.JavaFunctionCallException: An exception occurred while trying to execute function  `RSAHelper.signString(java.lang.String, java.lang.String, java.lang.String)`.
Caused by: java.lang.IllegalAccessError: class RSAHelper (in unnamed module @0x2b2ee070) cannot access class sun.security.util.DerInputStream (in module java.base) because module java.base does not export sun.security.util to unnamed module @0x2b2ee070
	RSAHelper.getPrivatePKCS1Pem(RSAHelper.java:32)
	RSAHelper.signString(RSAHelper.java:16)
	jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
	jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	java.lang.reflect.Method.invoke(Method.java:568)

Unknown location
Trace:
  at invoke (line: -1, column: -1)
  at signString (line: -1, column: -1)
  at jwt::RSA::signJWT (line: 55, column: 5)
  at jwt::RSA::JWT (line: 121, column: 15)
  at anonymous::main (line: 9, column: 9)

...

Root Exception stack trace:
org.mule.runtime.api.el.ExpressionExecutionException: org.mule.weave.v2.module.pojo.exception.JavaFunctionCallException: An exception occurred while trying to execute function  `RSAHelper.signString(java.lang.String, java.lang.String, java.lang.String)`.
Caused by: java.lang.IllegalAccessError: class RSAHelper (in unnamed module @0x2b2ee070) cannot access class sun.security.util.DerInputStream (in module java.base) because module java.base does not export sun.security.util to unnamed module @0x2b2ee070
	RSAHelper.getPrivatePKCS1Pem(RSAHelper.java:32)
	RSAHelper.signString(RSAHelper.java:16)
	jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
	jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	java.lang.reflect.Method.invoke(Method.java:568)

Unknown location
Trace:
  at invoke (line: -1, column: -1)
  at signString (line: -1, column: -1)
  at jwt::RSA::signJWT (line: 55, column: 5)
  at jwt::RSA::JWT (line: 121, column: 15)
  at anonymous::main (line: 9, column: 9)

	at org.mule.weave.mule.service.weave/org.mule.weave.v2.el.utils.ExceptionHandler$.handleLocatableException(ExceptionHandler.scala:29)
	at org.mule.weave.mule.service.weave/org.mule.weave.v2.el.WeaveExpressionLanguageSession.doEvaluate(WeaveExpressionLanguageSession.scala:276)
	at org.mule.weave.mule.service.weave/org.mule.weave.v2.el.WeaveExpressionLanguageSession.evaluate(WeaveExpressionLanguageSession.scala:121)
	at org.mule.runtime.core@4.6.2/org.mule.runtime.core.internal.el.dataweave.DataWeaveExpressionLanguageAdaptor$1.evaluate(DataWeaveExpressionLanguageAdaptor.java:372)
	at org.mule.runtime.core@4.6.2/org.mule.runtime.core.internal.el.DefaultExpressionManagerSession.evaluate(DefaultExpressionManagerSession.java:105)
	at com.mulesoft.mule.runtime.core.ee@4.6.2/com.mulesoft.mule.runtime.core.internal.processor.SetPayloadTransformationTarget.process(SetPayloadTransformationTarget.java:29)
	at com.mulesoft.mule.runtime.core.ee@4.6.2/com.mulesoft.mule.runtime.core.internal.processor.TransformMessageProcessor.lambda$process$0(TransformMessageProcessor.java:89)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at com.mulesoft.mule.runtime.core.ee@4.6.2/com.mulesoft.mule.runtime.core.internal.processor.TransformMessageProcessor.process(TransformMessageProcessor.java:89)
	at org.mule.runtime.core@4.6.2/org.mule.runtime.core.api.util.func.CheckedFunction.apply(CheckedFunction.java:25)
	at org.mule.runtime.core@4.6.2/org.mule.runtime.core.api.rx.Exceptions.lambda$checkedFunction$2(Exceptions.java:85)
	at org.mule.runtime.core@4.6.2/org.mule.runtime.core.internal.util.rx.Operators.lambda$nullSafeMap$0(Operators.java:47)
	at reactor.core@3.4.22/reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.onNext(FluxHandleFuseable.java:176)
	at org.mule.runtime.core@4.6.2/org.mule.runtime.core.privileged.processor.chain.AbstractMessageProcessorChain$2.onNext(AbstractMessageProcessorChain.java:629)
	at org.mule.runtime.core@4.6.2/org.mule.runtime.core.privileged.processor.chain.AbstractMessageProcessorChain$2.onNext(AbstractMessageProcessorChain.java:624)
	at reactor.core@3.4.22/reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onNext(FluxHide.java:137)
	at reactor.core@3.4.22/reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:210)
	at reactor.core@3.4.22/reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onNext(FluxOnAssembly.java:539)
	at reactor.core@3.4.22/reactor.core.publisher.FluxSubscribeOnValue$ScheduledScalar.run(FluxSubscribeOnValue.java:180)
	at reactor.core@3.4.22/reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
	at reactor.core@3.4.22/reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.mule.service.scheduler@1.6.2/org.mule.service.scheduler.internal.AbstractRunnableFutureDecorator.doRun(AbstractRunnableFutureDecorator.java:180)
	at org.mule.service.scheduler@1.6.2/org.mule.service.scheduler.internal.RunnableFutureDecorator.run(RunnableFutureDecorator.java:55)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

********************************************************************************
```

**Comment by afelisatti** [comment]
Hi, @uccu-jacobh. Our plan is to update this library to include Java 17 supportability but we haven't released a new version yet.

**Comment by MarcoSorace** [comment]
Hi @afelisatti the error persists, when will it be updated?

**Comment by uccu-jacobh** [comment]
This appears to be fixed in version 1.0.1
